### ISSUE TITLE
Exception on evaluator - Prelude.last: empty list

### ISSUE THREAD

**Issue by utdemir** [hercules-ci/support#21]
Hi,

One of my repos started failing to evaluate, as shown in the screenshot:

![2019-06-27-204918_1224x353_scrot](https://user-images.githubusercontent.com/928084/60251862-735bad00-991d-11e9-9181-f502b9c9d1ee.png)

I don't remember what I did, but it might be about some GitHub permissions; however currently the permissions look ok.

**Comment by roberth** [comment]
Hi Utku,

Thanks for reporting! This is actually a [bug](https://github.com/hercules-ci/hercules-ci-agent/issues/79) in the agent.
Do you think it's feasible to use attribute sets instead of a list in `ci.nix`? Doing so will fix the problem for your project and provide a better experience in the UI. You may need to use `pkgs.recurseIntoAttrs`, but only if you're going to nest attribute sets.

As to why it stopped working: older versions of the agent only looked at `default.nix`, so it seems that an update of the agent has broken your project by picking a different file.

**Comment by utdemir** [comment]
Hi @roberth.

Thank you for the quick answer. I modified the `ci.nix` to return an attribute set instead of a list and the issue is resolved :).

Thank you very much.
